<?php
/**
 * UploadsApi
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Psr7\Utils;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;
use OpenAPI\Client\Model\LobError;
use Jean85\PrettyVersions;

/**
 * UploadsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UploadsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    protected $customHeaders;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        Configuration $config = null,
        ClientInterface $client = null,
        HeaderSelector $selector = null,
        $customHeaders = [],
        $hostIndex = 0
    ) {
        $this->config = $config ?: new Configuration();
        $this->client = $client ?: new Client();
        $this->customHeaders = $customHeaders;
        $this->headerSelector = $selector ?: new HeaderSelector();

    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    private function modified_build(array $params, $encoding = PHP_QUERY_RFC3986): string
    {
        if (!$params) {
            return '';
        }

        if ($encoding === false) {
            $encoder = function (string $str): string {
                return $str;
            };
        } elseif ($encoding === PHP_QUERY_RFC3986) {
            $encoder = 'rawurlencode';
        } elseif ($encoding === PHP_QUERY_RFC1738) {
            $encoder = 'urlencode';
        } else {
            throw new \InvalidArgumentException('Invalid type');
        }

        $qs = '';
        foreach ($params as $k => $v) {
            $k = $encoder((string) $k);
            if (!is_array($v)) {
                $qs .= $k;
                if (is_bool($v)) {
                    $v = $v ? 'True' : 'False';
                }
                if (is_object($v)) {
                    $v = \GuzzleHttp\json_encode($v);
                }
                if ($v !== null) {
                    $qs .= '=' . $encoder((string) $v);
                }
                $qs .= '&';
            } else {
                foreach ($v as $kk=>$vv) {
                    $qs .= $k;
                    $vv = is_bool($vv) ? (int) $vv : $vv;
                    if ($vv !== null) {
                        $qs .= '[' . $kk . "]=" . $encoder((string) $vv);
                    }
                    $qs .= '&';
                }
            }
        }

        return $qs ? (string) substr($qs, 0, -1) : '';
    }

    /**
     * Operation get_export
     *
     * get_export
     *
     * @param  string $upl_id ID of the upload (required)
     * @param  string $ex_id ID of the export (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Export
     */
    public function get_export($upl_id, $ex_id)
    {
        $response = $this->get_exportWithHttpInfo($upl_id, $ex_id);
        return $response;
    }

    /**
     * Operation get_exportWithHttpInfo
     *
     * get_export
     *
     * @param  string $upl_id ID of the upload (required)
     * @param  string $ex_id ID of the export (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Export, HTTP status code, HTTP response headers (array of strings)
     */
    public function get_exportWithHttpInfo($upl_id, $ex_id)
    {
        $request = $this->get_exportRequest($upl_id, $ex_id);

        try {
            $options = $this->createHttpClientOption();
            $requestError = null;
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                $errorBody = json_decode($e->getResponse()->getBody()->getContents())->error;
                $requestError = new LobError();
                $requestError->setMessage(get_object_vars($errorBody)["message"]);
                $requestError->setStatusCode(get_object_vars($errorBody)["status_code"]);
                $requestError->setCode(get_object_vars($errorBody)["code"]);

                $exception = new ApiException($requestError->getMessage(), $requestError->getStatusCode(), null, null);
                throw $exception;
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            // This catches any non-successful status
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            // Since all non successes are thrown above, we can assume success
            $content = (string) $response->getBody();
            return ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Export', []);

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Create request for operation 'get_export'
     *
     * @param  string $upl_id ID of the upload (required)
     * @param  string $ex_id ID of the export (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function get_exportRequest($upl_id, $ex_id)
    {
        // verify the required parameter 'upl_id' is set
        if ($upl_id === null || (is_array($upl_id) && count($upl_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upl_id when calling get_export'
            );
        }
        if (!preg_match("/^upl_[a-zA-Z0-9]+$/", $upl_id)) {
            throw new \InvalidArgumentException("invalid value for \"upl_id\" when calling UploadsApi.get_export, must conform to the pattern /^upl_[a-zA-Z0-9]+$/.");
        }

        // verify the required parameter 'ex_id' is set
        if ($ex_id === null || (is_array($ex_id) && count($ex_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ex_id when calling get_export'
            );
        }
        if (!preg_match("/^ex_[a-zA-Z0-9]+$/", $ex_id)) {
            throw new \InvalidArgumentException("invalid value for \"ex_id\" when calling UploadsApi.get_export, must conform to the pattern /^ex_[a-zA-Z0-9]+$/.");
        }


        $resourcePath = '/uploads/{upl_id}/exports/{ex_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';



        // path params
        if ($upl_id !== null) {
            $resourcePath = str_replace(
                '{' . 'upl_id' . '}',
                ObjectSerializer::toPathValue($upl_id),
                $resourcePath
            );
        }
        // path params
        if ($ex_id !== null) {
            $resourcePath = str_replace(
                '{' . 'ex_id' . '}',
                ObjectSerializer::toPathValue($ex_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        );

        // for model (json/xml)


        $defaultHeaders = [];
        $version = PrettyVersions::getVersion('lob/lob-php')->getPrettyVersion();
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = "lob/lob-php/$version";
        }

        $customHeaders = $this->headerSelector->customHeaders($this->customHeaders);

        $headers = array_merge(
            $customHeaders,
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = $this->modified_build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation create_upload
     *
     * create_upload
     *
     * @param  \OpenAPI\Client\Model\UploadWritable $upload_writable upload_writable (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Upload|\OpenAPI\Client\Model\LobError
     */
    public function create_upload($upload_writable)
    {
        $response = $this->create_uploadWithHttpInfo($upload_writable);
        return $response;
    }

    /**
     * Operation create_uploadWithHttpInfo
     *
     * create_upload
     *
     * @param  \OpenAPI\Client\Model\UploadWritable $upload_writable (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Upload|\OpenAPI\Client\Model\LobError, HTTP status code, HTTP response headers (array of strings)
     */
    public function create_uploadWithHttpInfo($upload_writable)
    {
        $request = $this->create_uploadRequest($upload_writable);

        try {
            $options = $this->createHttpClientOption();
            $requestError = null;
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                $errorBody = json_decode($e->getResponse()->getBody()->getContents())->error;
                $requestError = new LobError();
                $requestError->setMessage(get_object_vars($errorBody)["message"]);
                $requestError->setStatusCode(get_object_vars($errorBody)["status_code"]);
                $requestError->setCode(get_object_vars($errorBody)["code"]);

                $exception = new ApiException($requestError->getMessage(), $requestError->getStatusCode(), null, null);
                throw $exception;
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            // This catches any non-successful status
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            // Since all non successes are thrown above, we can assume success
            $content = (string) $response->getBody();
            return ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Upload', []);

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Create request for operation 'create_upload'
     *
     * @param  \OpenAPI\Client\Model\UploadWritable $upload_writable (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function create_uploadRequest($upload_writable)
    {
        // verify the required parameter 'upload_writable' is set
        if ($upload_writable === null || (is_array($upload_writable) && count($upload_writable) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upload_writable when calling create_upload'
            );
        }

        $resourcePath = '/uploads';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        // for model (json/xml)
        if (isset($upload_writable)) {
            $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($upload_writable));
        }

        $defaultHeaders = [];
        $version = PrettyVersions::getVersion('lob/lob-php')->getPrettyVersion();
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = "lob/lob-php/$version";
        }

        $customHeaders = $this->headerSelector->customHeaders($this->customHeaders);

        $headers = array_merge(
            $customHeaders,
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = $this->modified_build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation delete_upload
     *
     * delete_upload
     *
     * @param  string $upl_id id of the upload (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function delete_upload($upl_id)
    {
        $this->delete_uploadWithHttpInfo($upl_id);
    }

    /**
     * Operation delete_uploadWithHttpInfo
     *
     * delete_upload
     *
     * @param  string $upl_id id of the upload (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function delete_uploadWithHttpInfo($upl_id)
    {
        $request = $this->delete_uploadRequest($upl_id);

        try {
            $options = $this->createHttpClientOption();
            $requestError = null;
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                $errorBody = json_decode($e->getResponse()->getBody()->getContents())->error;
                $requestError = new LobError();
                $requestError->setMessage(get_object_vars($errorBody)["message"]);
                $requestError->setStatusCode(get_object_vars($errorBody)["status_code"]);
                $requestError->setCode(get_object_vars($errorBody)["code"]);

                $exception = new ApiException($requestError->getMessage(), $requestError->getStatusCode(), null, null);
                throw $exception;
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            // This catches any non-successful status
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Create request for operation 'delete_upload'
     *
     * @param  string $upl_id id of the upload (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function delete_uploadRequest($upl_id)
    {
        // verify the required parameter 'upl_id' is set
        if ($upl_id === null || (is_array($upl_id) && count($upl_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upl_id when calling delete_upload'
            );
        }
        if (!preg_match("/^upl_[a-zA-Z0-9]+$/", $upl_id)) {
            throw new \InvalidArgumentException("invalid value for \"upl_id\" when calling UploadsApi.delete_upload, must conform to the pattern /^upl_[a-zA-Z0-9]+$/.");
        }


        $resourcePath = '/uploads/{upl_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';



        // path params
        if ($upl_id !== null) {
            $resourcePath = str_replace(
                '{' . 'upl_id' . '}',
                ObjectSerializer::toPathValue($upl_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        );

        // for model (json/xml)


        $defaultHeaders = [];
        $version = PrettyVersions::getVersion('lob/lob-php')->getPrettyVersion();
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = "lob/lob-php/$version";
        }

        $customHeaders = $this->headerSelector->customHeaders($this->customHeaders);

        $headers = array_merge(
            $customHeaders,
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = $this->modified_build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation create_export
     *
     * create_export
     *
     * @param  string $upl_id ID of the upload (required)
     * @param  \OpenAPI\Client\Model\ExportModel $export_model export_model (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\UploadCreateExport|\OpenAPI\Client\Model\LobError
     */
    public function create_export($upl_id, $export_model)
    {
        $response = $this->create_exportWithHttpInfo($upl_id, $export_model);
        return $response;
    }

    /**
     * Operation create_exportWithHttpInfo
     *
     * create_export
     *
     * @param  string $upl_id ID of the upload (required)
     * @param  \OpenAPI\Client\Model\ExportModel $export_model (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UploadCreateExport|\OpenAPI\Client\Model\LobError, HTTP status code, HTTP response headers (array of strings)
     */
    public function create_exportWithHttpInfo($upl_id, $export_model)
    {
        $request = $this->create_exportRequest($upl_id, $export_model);

        try {
            $options = $this->createHttpClientOption();
            $requestError = null;
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                $errorBody = json_decode($e->getResponse()->getBody()->getContents())->error;
                $requestError = new LobError();
                $requestError->setMessage(get_object_vars($errorBody)["message"]);
                $requestError->setStatusCode(get_object_vars($errorBody)["status_code"]);
                $requestError->setCode(get_object_vars($errorBody)["code"]);

                $exception = new ApiException($requestError->getMessage(), $requestError->getStatusCode(), null, null);
                throw $exception;
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            // This catches any non-successful status
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            // Since all non successes are thrown above, we can assume success
            $content = (string) $response->getBody();
            return ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\UploadCreateExport', []);

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Create request for operation 'create_export'
     *
     * @param  string $upl_id ID of the upload (required)
     * @param  \OpenAPI\Client\Model\ExportModel $export_model (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function create_exportRequest($upl_id, $export_model)
    {
        // verify the required parameter 'upl_id' is set
        if ($upl_id === null || (is_array($upl_id) && count($upl_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upl_id when calling create_export'
            );
        }
        if (!preg_match("/^upl_[a-zA-Z0-9]+$/", $upl_id)) {
            throw new \InvalidArgumentException("invalid value for \"upl_id\" when calling UploadsApi.create_export, must conform to the pattern /^upl_[a-zA-Z0-9]+$/.");
        }

        // verify the required parameter 'export_model' is set
        if ($export_model === null || (is_array($export_model) && count($export_model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $export_model when calling create_export'
            );
        }

        $resourcePath = '/uploads/{upl_id}/exports';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';



        // path params
        if ($upl_id !== null) {
            $resourcePath = str_replace(
                '{' . 'upl_id' . '}',
                ObjectSerializer::toPathValue($upl_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        // for model (json/xml)
        if (isset($export_model)) {
            $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($export_model));
        }

        $defaultHeaders = [];
        $version = PrettyVersions::getVersion('lob/lob-php')->getPrettyVersion();
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = "lob/lob-php/$version";
        }

        $customHeaders = $this->headerSelector->customHeaders($this->customHeaders);

        $headers = array_merge(
            $customHeaders,
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = $this->modified_build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation upload_file
     *
     * upload_file
     *
     * @param  string $upl_id ID of the upload (required)
     * @param  mixed $file file (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\UploadFile|\OpenAPI\Client\Model\HTTPValidationError
     */
    public function upload_file($upl_id, $file)
    {
        $response = $this->upload_fileWithHttpInfo($upl_id, $file);
        return $response;
    }

    /**
     * Operation upload_fileWithHttpInfo
     *
     * upload_file
     *
     * @param  string $upl_id ID of the upload (required)
     * @param  mixed $file (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UploadFile|\OpenAPI\Client\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function upload_fileWithHttpInfo($upl_id, $file)
    {
        $request = $this->upload_fileRequest($upl_id, $file);

        try {
            $options = $this->createHttpClientOption();
            $requestError = null;
            try {
                $response = $this->client->request(
                    'POST',
                    $request->getUri()->__toString(),
                    [
                        'multipart' => [[
                            'name' => 'file',
                            'contents' => Utils::tryFopen('/Users/jessica-ho/Desktop/lob-php/test/assets/lobster-family.csv', 'r')
                        ]],
                        'auth' => $options['auth']
                    ]
                );
            } catch (RequestException $e) {
                $errorBody = json_decode($e->getResponse()->getBody()->getContents())->error;
                $requestError = new LobError();
                $requestError->setMessage(get_object_vars($errorBody)["message"]);
                $requestError->setStatusCode(get_object_vars($errorBody)["status_code"]);
                $requestError->setCode(get_object_vars($errorBody)["code"]);

                $exception = new ApiException($requestError->getMessage(), $requestError->getStatusCode(), null, null);
                throw $exception;
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            // This catches any non-successful status
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            // Since all non successes are thrown above, we can assume success
            $content = (string) $response->getBody();
            return ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\UploadFile', []);

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Create request for operation 'upload_file'
     *
     * @param  string $upl_id ID of the upload (required)
     * @param  mixed $file (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function upload_fileRequest($upl_id, $file)
    {
        // verify the required parameter 'upl_id' is set
        if ($upl_id === null || (is_array($upl_id) && count($upl_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upl_id when calling upload_file'
            );
        }
        if (!preg_match("/^upl_[a-zA-Z0-9]+$/", $upl_id)) {
            throw new \InvalidArgumentException("invalid value for \"upl_id\" when calling UploadsApi.upload_file, must conform to the pattern /^upl_[a-zA-Z0-9]+$/.");
        }

        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling upload_file'
            );
        }

        $resourcePath = '/uploads/{upl_id}/file';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';



        // path params
        if ($upl_id !== null) {
            $resourcePath = str_replace(
                '{' . 'upl_id' . '}',
                ObjectSerializer::toPathValue($upl_id),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $formParams['file'] = ObjectSerializer::toFormValue($file);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['multipart/form-data']
        );

        // for model (json/xml)


        $defaultHeaders = [];
        $version = PrettyVersions::getVersion('lob/lob-php')->getPrettyVersion();
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = "lob/lob-php/$version";
        }

        $customHeaders = $this->headerSelector->customHeaders($this->customHeaders);

        $headers = array_merge(
            $customHeaders,
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = $this->modified_build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation get_upload
     *
     * get_upload
     *
     * @param  string $upl_id id of the upload (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Upload|\OpenAPI\Client\Model\LobError
     */
    public function get_upload($upl_id)
    {
        $response = $this->get_uploadWithHttpInfo($upl_id);
        return $response;
    }

    /**
     * Operation get_uploadWithHttpInfo
     *
     * get_upload
     *
     * @param  string $upl_id id of the upload (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Upload|\OpenAPI\Client\Model\LobError, HTTP status code, HTTP response headers (array of strings)
     */
    public function get_uploadWithHttpInfo($upl_id)
    {
        $request = $this->get_uploadRequest($upl_id);

        try {
            $options = $this->createHttpClientOption();
            $requestError = null;
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                $errorBody = json_decode($e->getResponse()->getBody()->getContents())->error;
                $requestError = new LobError();
                $requestError->setMessage(get_object_vars($errorBody)["message"]);
                $requestError->setStatusCode(get_object_vars($errorBody)["status_code"]);
                $requestError->setCode(get_object_vars($errorBody)["code"]);

                $exception = new ApiException($requestError->getMessage(), $requestError->getStatusCode(), null, null);
                throw $exception;
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            // This catches any non-successful status
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            // Since all non successes are thrown above, we can assume success
            $content = (string) $response->getBody();
            return ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Upload', []);

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Create request for operation 'get_upload'
     *
     * @param  string $upl_id id of the upload (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function get_uploadRequest($upl_id)
    {
        // verify the required parameter 'upl_id' is set
        if ($upl_id === null || (is_array($upl_id) && count($upl_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upl_id when calling get_upload'
            );
        }
        if (!preg_match("/^upl_[a-zA-Z0-9]+$/", $upl_id)) {
            throw new \InvalidArgumentException("invalid value for \"upl_id\" when calling UploadsApi.get_upload, must conform to the pattern /^upl_[a-zA-Z0-9]+$/.");
        }


        $resourcePath = '/uploads/{upl_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';



        // path params
        if ($upl_id !== null) {
            $resourcePath = str_replace(
                '{' . 'upl_id' . '}',
                ObjectSerializer::toPathValue($upl_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        );

        // for model (json/xml)


        $defaultHeaders = [];
        $version = PrettyVersions::getVersion('lob/lob-php')->getPrettyVersion();
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = "lob/lob-php/$version";
        }

        $customHeaders = $this->headerSelector->customHeaders($this->customHeaders);

        $headers = array_merge(
            $customHeaders,
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = $this->modified_build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation update_upload
     *
     * update_upload
     *
     * @param  string $upl_id id of the upload (required)
     * @param  \OpenAPI\Client\Model\UploadUpdatable $upload_updatable upload_updatable (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Upload|\OpenAPI\Client\Model\LobError
     */
    public function update_upload($upl_id, $upload_updatable)
    {
        $response = $this->update_uploadWithHttpInfo($upl_id, $upload_updatable);
        return $response;
    }

    /**
     * Operation update_uploadWithHttpInfo
     *
     * update_upload
     *
     * @param  string $upl_id id of the upload (required)
     * @param  \OpenAPI\Client\Model\UploadUpdatable $upload_updatable (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Upload|\OpenAPI\Client\Model\LobError, HTTP status code, HTTP response headers (array of strings)
     */
    public function update_uploadWithHttpInfo($upl_id, $upload_updatable)
    {
        $request = $this->update_uploadRequest($upl_id, $upload_updatable);

        try {
            $options = $this->createHttpClientOption();
            $requestError = null;
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                $errorBody = json_decode($e->getResponse()->getBody()->getContents())->error;
                $requestError = new LobError();
                $requestError->setMessage(get_object_vars($errorBody)["message"]);
                $requestError->setStatusCode(get_object_vars($errorBody)["status_code"]);
                $requestError->setCode(get_object_vars($errorBody)["code"]);

                $exception = new ApiException($requestError->getMessage(), $requestError->getStatusCode(), null, null);
                throw $exception;
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            // This catches any non-successful status
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            // Since all non successes are thrown above, we can assume success
            $content = (string) $response->getBody();
            return ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Upload', []);

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Create request for operation 'update_upload'
     *
     * @param  string $upl_id id of the upload (required)
     * @param  \OpenAPI\Client\Model\UploadUpdatable $upload_updatable (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function update_uploadRequest($upl_id, $upload_updatable)
    {
        // verify the required parameter 'upl_id' is set
        if ($upl_id === null || (is_array($upl_id) && count($upl_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upl_id when calling update_upload'
            );
        }
        if (!preg_match("/^upl_[a-zA-Z0-9]+$/", $upl_id)) {
            throw new \InvalidArgumentException("invalid value for \"upl_id\" when calling UploadsApi.update_upload, must conform to the pattern /^upl_[a-zA-Z0-9]+$/.");
        }

        // verify the required parameter 'upload_updatable' is set
        if ($upload_updatable === null || (is_array($upload_updatable) && count($upload_updatable) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upload_updatable when calling update_upload'
            );
        }

        $resourcePath = '/uploads/{upl_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';



        // path params
        if ($upl_id !== null) {
            $resourcePath = str_replace(
                '{' . 'upl_id' . '}',
                ObjectSerializer::toPathValue($upl_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        // for model (json/xml)
        if (isset($upload_updatable)) {
            $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($upload_updatable));
        }

        $defaultHeaders = [];
        $version = PrettyVersions::getVersion('lob/lob-php')->getPrettyVersion();
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = "lob/lob-php/$version";
        }

        $customHeaders = $this->headerSelector->customHeaders($this->customHeaders);

        $headers = array_merge(
            $customHeaders,
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = $this->modified_build($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation list_upload
     *
     * list_upload
     *
     * @param  string $campaign_id id of the campaign (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Upload[]
     */
    public function list_upload($campaign_id = null)
    {
        $response = $this->list_uploadWithHttpInfo($campaign_id);
        return $response;
    }

    /**
     * Operation list_uploadWithHttpInfo
     *
     * list_upload
     *
     * @param  string $campaign_id id of the campaign (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Upload[], HTTP status code, HTTP response headers (array of strings)
     */
    public function list_uploadWithHttpInfo($campaign_id = null)
    {
        $request = $this->list_uploadRequest($campaign_id);

        try {
            $options = $this->createHttpClientOption();
            $requestError = null;
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                $errorBody = json_decode($e->getResponse()->getBody()->getContents())->error;
                $requestError = new LobError();
                $requestError->setMessage(get_object_vars($errorBody)["message"]);
                $requestError->setStatusCode(get_object_vars($errorBody)["status_code"]);
                $requestError->setCode(get_object_vars($errorBody)["code"]);

                $exception = new ApiException($requestError->getMessage(), $requestError->getStatusCode(), null, null);
                throw $exception;
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            // This catches any non-successful status
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            // Since all non successes are thrown above, we can assume success
            $content = (string) $response->getBody();
            return ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Upload[]', []);

        } catch (ApiException $e) {
            throw $e;
        }
    }

    /**
     * Create request for operation 'list_upload'
     *
     * @param  string $campaign_id id of the campaign (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function list_uploadRequest($campaign_id = null)
    {
        if ($campaign_id !== null && !preg_match("/^cmp_[a-zA-Z0-9]+$/", $campaign_id)) {
            throw new \InvalidArgumentException("invalid value for \"campaign_id\" when calling UploadsApi.list_upload, must conform to the pattern /^cmp_[a-zA-Z0-9]+$/.");
        }


        $resourcePath = '/uploads';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';

        // query params
        if ($campaign_id !== null) {
            $queryParams['campaignId'] = $campaign_id;
        }




        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            []
        );

        // for model (json/xml)


        $defaultHeaders = [];
        $version = PrettyVersions::getVersion('lob/lob-php')->getPrettyVersion();
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = "lob/lob-php/$version";
        }

        $customHeaders = $this->headerSelector->customHeaders($this->customHeaders);

        $headers = array_merge(
            $customHeaders,
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = $this->modified_build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = array(
            'headers' => array(
                'Accept' => 'application/json; charset=utf-8',
                'User-Agent' => 'Lob/v1 PhpBindings/' . 'TODO', // TODO
            ),
            'auth' => array($this->getConfig()->getApiKey('basic'), '')
        );
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
