<?php
/**
 * DpvFootnote
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DpvFootnote Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum DpvFootnote: string
{
    /**
     * Possible values of this enum
     */
    case AA = 'AA';

    case A1 = 'A1';

    case BB = 'BB';

    case CC = 'CC';

    case C1 = 'C1';

    case F1 = 'F1';

    case G1 = 'G1';

    case IA = 'IA';

    case M1 = 'M1';

    case M3 = 'M3';

    case N1 = 'N1';

    case PB = 'PB';

    case P1 = 'P1';

    case P3 = 'P3';

    case R1 = 'R1';

    case R7 = 'R7';

    case RR = 'RR';

    case TA = 'TA';

    case U1 = 'U1';

}


