<?php
/**
 * AddressEditableTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use OpenAPI\Client\Model\AddressEditable;
use OpenAPI\Client\Model\CountryExtended;
use PHPUnit\Framework\TestCase;

/**
 * AddressEditableTest Class Doc Comment
 *
 * @category    Class
 * @description AddressEditable
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddressEditableTest extends TestCase
{

    /**
     * Test attribute "address_line1"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressLine1()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setAddressLine1("fake");
        $this->assertEquals($address->getAddressLine1(), "fake");

        // Construction
        $address = new AddressEditable(["address_line1" => "fake2"]);
        $this->assertEquals($address->getAddressLine1(), "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["address_line1"] = "fake3";
        $this->assertEquals($address->getAddressLine1(), "fake3");
    }

    /**
     * Test attribute "address_line1"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressLine1Exception()
    {
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setAddressLine1(str_repeat("N", 250));
    }

    /**
     * Test attribute "address_line2"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressLine2()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setAddressLine2("fake");
        $this->assertEquals($address->getAddressLine2(), "fake");

        // Construction
        $address = new AddressEditable(["address_line2" => "fake2"]);
        $this->assertEquals($address->getAddressLine2(), "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["address_line2"] = "fake3";
        $this->assertEquals($address->getAddressLine2(), "fake3");
    }

    /**
     * Test attribute "address_line2"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressLine2Exception()
    {
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setAddressLine2(str_repeat("N", 225));
    }

    /**
     * Test attribute "address_city"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressCity()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setAddressCity("fake");
        $this->assertEquals($address->getAddressCity(), "fake");

        // Construction
        $address = new AddressEditable(["address_city" => "fake2"]);
        $this->assertEquals($address->getAddressCity(), "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["address_city"] = "fake3";
        $this->assertEquals($address->getAddressCity(), "fake3");
    }

    /**
     * Test attribute "city"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressCityException()
    {
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setAddressCity(str_repeat("N", 300));
    }

    /**
     * Test attribute "address_state"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressState()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setAddressState("fake");
        $this->assertEquals($address->getAddressState(), "fake");

        // Construction
        $address = new AddressEditable(["address_state" => "fake2"]);
        $this->assertEquals($address->getAddressState(), "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["address_state"] = "fake3";
        $this->assertEquals($address->getAddressState(), "fake3");
    }

    /**
     * Test attribute "address_state"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressStateException()
    {
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setAddressState(str_repeat("N", 201));
    }

    /**
     * Test attribute "address_zip"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressZip()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setAddressZip("fake");
        $this->assertEquals($address->getAddressZip(), "fake");

        // Construction
        $address = new AddressEditable(["address_zip" => "fake2"]);
        $this->assertEquals($address->getAddressZip(), "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["address_zip"] = "fake3";
        $this->assertEquals($address->getAddressZip(), "fake3");
    }

    /**
     * Test attribute "address_zip"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressZipException()
    {
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setAddressZip(str_repeat("N", 41));
    }

    /**
     * Test attribute "address_country"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyAddressCountry()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setAddressCountry(CountryExtended::US);
        $this->assertEquals($address->getAddressCountry(), CountryExtended::US);

        // Construction
        $address = new AddressEditable(["address_country" => CountryExtended::GB]);
        $this->assertEquals($address->getAddressCountry(), CountryExtended::GB);

        // Array Access
        $address = new AddressEditable();
        $address["address_country"] = CountryExtended::FR;
        $this->assertEquals($address->getAddressCountry(), CountryExtended::FR);
    }

    /**
     * Test attribute "description"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyDescription()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setDescription("fake");
        $this->assertEquals($address->getDescription(), "fake");

        // Construction
        $address = new AddressEditable(["description" => "fake2"]);
        $this->assertEquals($address->getDescription(), "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["description"] = "fake3";
        $this->assertEquals($address->getDescription(), "fake3");
    }

    /**
     * Test attribute "description"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyDescriptionException()
    {
        // Procedural
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setDescription(str_repeat("N", 300));
    }

    /**
     * Test attribute "name"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyName()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setName("fake");
        $this->assertEquals($address->getName(), "fake");

        // Construction
        $address = new AddressEditable(["name" => "fake2"]);
        $this->assertEquals($address->getName(), "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["name"] = "fake3";
        $this->assertEquals($address->getName(), "fake3");
    }

    /**
     * Test attribute "name"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyNameException()
    {
        // Procedural
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setName(str_repeat("N", 100));
    }

    /**
     * Test attribute "company"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyCompany()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setCompany("fake");
        $this->assertEquals($address->getCompany(), "fake");

        // Construction
        $address = new AddressEditable(["company" => "fake2"]);
        $this->assertEquals($address->getCompany(), "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["company"] = "fake3";
        $this->assertEquals($address->getCompany(), "fake3");
    }

    /**
     * Test attribute "company"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyCompanyException()
    {
        // Procedural
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setCompany(str_repeat("N", 41));
    }

    /**
     * Test attribute "phone"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyPhone()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setPhone("fake");
        $this->assertEquals($address->getPhone(), "fake");

        // Construction
        $address = new AddressEditable(["phone" => "fake2"]);
        $this->assertEquals($address->getPhone(), "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["phone"] = "fake3";
        $this->assertEquals($address->getPhone(), "fake3");
    }

    /**
     * Test attribute "phone"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyPhoneException()
    {
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setPhone(str_repeat("N", 100));
    }

    /**
     * Test attribute "email"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyEmail()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setEmail("fake@email.com");
        $this->assertEquals($address->getEmail(), "fake@email.com");

        // Construction
        $address = new AddressEditable(["email" => "fake2@email.com"]);
        $this->assertEquals($address->getEmail(), "fake2@email.com");

        // Array Access
        $address = new AddressEditable();
        $address["email"] = "fake3@email.com";
        $this->assertEquals($address->getEmail(), "fake3@email.com");
    }

    /**
     * Test attribute "email"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyEmailException()
    {
        $address = new AddressEditable();
        $this->expectException(\InvalidArgumentException::class);
        $address->setEmail(str_repeat("N", 200));
    }

    /**
     * Test attribute "metadata"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyMetadata()
    {
        // Procedural
        $address = new AddressEditable();
        $address->setMetadata(["campaign" => "fake"]);
        $this->assertEquals($address->getMetadata()["campaign"], "fake");

        // Construction
        $address = new AddressEditable(["metadata" => ["campaign" => "fake2"]]);
        $this->assertEquals($address->getMetadata()["campaign"], "fake2");

        // Array Access
        $address = new AddressEditable();
        $address["metadata"] = ["campaign" => "fake3"];
        $this->assertEquals($address->getMetadata()["campaign"], "fake3");
    }

    /** **** **** **** **** **** **/
    /**  Generic Model Helpers   **/
    /** **** **** **** **** **** **/

    /**
     * Test attribute "ModelName"
     * @group address
     * @group unit
     * @group model
     */
    public function testPropertyModelName()
    {
        $address = new AddressEditable();
        $this->assertEquals($address->getModelName(), "address_editable");
    }

    /**
     * Test attribute "ListInvalidProperties"
     * @group address
     * @group unit
     * @group model
     */
    public function testValidProperties()
    {
        $address = new AddressEditable();
        $address["address_line1"] = str_repeat("N", 300);
        $address["address_line2"] = str_repeat("N", 300);
        $address["address_city"] = str_repeat("N", 225);
        $address["address_state"] = str_repeat("N", 225);
        $address["address_zip"] = str_repeat("N", 50);
        $address["description"] = str_repeat("N", 300);
        $address["name"] = str_repeat("N", 50);
        $address["company"] = str_repeat("N", 50);
        $address["phone"] = str_repeat("N", 50);
        $address["email"] = str_repeat("N", 150);

        $invalidPros = $address->listInvalidProperties();
        $this->assertEquals(count($invalidPros), 10);
        $this->assertEquals($address->valid(), false);
    }
}
