<?php
/**
 * CardOrderEditableTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use OpenAPI\Client\Model\CardOrderEditable;
use PHPUnit\Framework\TestCase;

/**
 * CardOrderEditableTest Class Doc Comment
 *
 * @category    Class
 * @description CardOrderEditable
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CardOrderEditableTest extends TestCase
{
    /**
     * Test attribute "quantity"
     * @group card
     * @group unit
     * @group model
     */
    public function testPropertyQuantity()
    {
        // Procedural
        $order = new CardOrderEditable();
        $order->setQuantity(1);
        $this->assertEquals($order->getQuantity(), 1);
    }

    /**
     * Test attribute "quantity"
     * @group card
     * @group unit
     * @group model
     */
    public function testPropertyQuantityExceptionLarge()
    {
        // Procedural
        $order = new CardOrderEditable();
        $this->expectException(\InvalidArgumentException::class);
        $order->setQuantity(10000001);
    }

    /**
     * Test attribute "quantity"
     * @group card
     * @group unit
     * @group model
     */
    public function testPropertyQuantityExceptionSmall()
    {
        // Procedural
        $order = new CardOrderEditable();
        $this->expectException(\InvalidArgumentException::class);
        $order->setQuantity(-1);
    }

    /** **** **** **** **** **** **/
    /**  Generic Model Helpers   **/
    /** **** **** **** **** **** **/

    /**
     * Test attribute "ModelName"
     * @group billing_group
     * @group unit
     * @group model
     */
    public function testPropertyModelName()
    {
        $order = new CardOrderEditable();
        $this->assertEquals($order->getModelName(), "card_order_editable");
    }

    /**
     * Test attribute "ListInvalidProperties"
     * @group billing_group
     * @group unit
     * @group model
     */
    public function testValidProperties()
    {
        $order = new CardOrderEditable();
        $order["quantity"] = 10000001;

        $invalidPros = $order->listInvalidProperties();
        $this->assertEquals(count($invalidPros), 1);
        $this->assertEquals($order->valid(), false);

        $order = new CardOrderEditable();
        $order["quantity"] = "NOPE";

        $invalidPros = $order->listInvalidProperties();
        $this->assertEquals(count($invalidPros), 1);

        $order = new CardOrderEditable();
        $order["quantity"] = -1;

        $invalidPros = $order->listInvalidProperties();
        $this->assertEquals(count($invalidPros), 1);
    }

    /**
     * Tests for alternative property accessors
     * @group billing_group
     * @group unit
     * @group model
     */
    public function testGenericProperties()
    {
        $list = new CardOrderEditable();
        $list->offsetSet('object', 'bank_account');
        $this->assertEquals($list->offsetExists('object'), true);
        $this->assertEquals($list->offsetGet('object'), 'bank_account');
        $list->offsetUnset('object');
        $this->assertEquals($list->offsetGet('object'), null);
    }
}
