name: Run Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main

jobs:
  php_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: php-actions/composer@v6

      - name: Run Unit Tests
        run: vendor/bin/phpunit --group unit--coverage-text --coverage-clover=coverage/coverage.xml --configuration=phpunit.xml.dist
        env:
          LOB_API_TEST_KEY: ${{ secrets.LOB_API_TEST_KEY }}
          LOB_API_LIVE_KEY: ${{ secrets.LOB_API_LIVE_KEY }}
          XDEBUG_MODE: coverage

      # TODO: Run Integration Tests
